<?php

namespace SejoursPatientsBundle\Repository;

/**
 * LitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LitRepository extends \Doctrine\ORM\EntityRepository
{
}
