<?php

namespace HopitalBundle\Repository;

/**
 * SejourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SejourRepository extends \Doctrine\ORM\EntityRepository
{
}
